services:
  api:
    build: ./api
    environment:
      NODE_ENV: production

  webui:
    build: ./webui
    restart: "no"
    volumes:
      - static_files:/output

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_files:/usr/share/nginx/html:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      api:
        condition: service_started
      webui:
        condition: service_completed_successfully

volumes:
  static_files:
  nginx_logs:
