#!/usr/bin/sh

docker compose up -d database

export DATABASE_PASSWORD_FILE="../secrets/postgres_password"
export DATABASE_USER_FILE="../secrets/postgres_user"
export DATABASE_NAME_FILE="../secrets/postgres_user"
export DATABASE_HOST="localhost"
export DATABASE_PORT="5432"

cd "$(dirname "$0")/.." || exit 1
(cd api && bun --bun dev) &&
(cd webui && bun --bun dev)
