#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.." || exit 1

# Start database
docker compose up -d database

set -a && source ../.env && set +a
export NODE_ENV="development"
export PUBLIC_HOST="${PUBLIC_HOST:-localhost:3000}"

# Run both dev servers in parallel
(cd api && bun --bun dev) &
(cd webui && bun --bun dev) &

wait
